name: Viewflow CI

on:
  push:
    branches: [ v2 ]

jobs:
  build:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: syphar/restore-virtualenv@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools==59.8.0
        python -m pip install tox
        tox --notest
    - name: Run Tests
      run: |
        tox -- coverage run --source='viewflow' ./manage.py test --exclude-tag=selenium --exclude-tag=integration
        tox -- coverage lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
